spring:
  profiles:
    include: oauth
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
  mvc:
    log-request-details: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
logging:
  level:
    org:
      springframework:
        web: debug
      hibernate:
        type: trace


